services:
  - type: web
    name: hublio-mivali
    runtime: node
    plan: free
    repo: https://github.com/ThabisoEugeneMaboe/hublio-mivali
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: node api/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "20"
